version: "3"
services:
  treasurehunt:
    build: .
    command: ["uvicorn", "treasurehunt.app:app", "--host", "0.0.0.0", "--port", "8069", "--log-level", "debug"]
    ports:
      - 8069:8069
    volumes:
      - ".:/app"
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
